{% set version = "3.0.9" %}

package:
  name: django-reversion
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-reversion/django-reversion-{{ version }}.tar.gz
  sha256: a5af55f086a3f9c38be2f049c251e06005b9ed48ba7a109473736b1fc95a066f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django >=1.8

test:
  imports:
    - reversion

about:
  home: https://github.com/etianen/django-reversion
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: django-reversion is an extension to the Django web framework that provides version control for model instances.
  description: django-reversion is an extension to the Django web framework that provides version control for model instances.
  doc_url: https://django-reversion.readthedocs.io/en/stable/
  dev_url: https://github.com/etianen/django-reversion

extra:
  recipe-maintainers:
    - cshaley
    - sannykr

