{% set name = "django-reversion" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3309821e5b6fceedcce6b6975f1a9c7fab6ae7c7d0e1276a90e345946fa0dcb8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - babel
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=3.2

test:
  imports:
    - reversion
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/etianen/django-reversion
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: django-reversion is an extension to the Django web framework that provides version control for model instances.
  description: django-reversion is an extension to the Django web framework that provides version control for model instances.
  doc_url: https://django-reversion.readthedocs.io/en/stable/
  dev_url: https://github.com/etianen/django-reversion

extra:
  recipe-maintainers:
    - elanqo
    - cshaley
    - sannykr
    - rxm7706
