{% set name = "django-reversion" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cab0fd90640b2ceb37d7a897823ca72a21b960ad1d6a3b9cb4e351fabbd27d9c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - babel
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=4.2

test:
  imports:
    - reversion
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/etianen/django-reversion
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: django-reversion is an extension to the Django web framework that provides version control for model instances.
  description: django-reversion is an extension to the Django web framework that provides version control for model instances.
  doc_url: https://django-reversion.readthedocs.io/en/stable/
  dev_url: https://github.com/etianen/django-reversion

extra:
  recipe-maintainers:
    - elanqo
    - cshaley
    - sannykr
    - rxm7706
